include:
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

default:
  image: ghcr.io/gulitsky/solidity-starter:latest
  tags:
    - build-solidity
  before_script:
    - yarn install --immutable
  cache:
    key:
      files:
        - ./yarn.lock
        - ./.yarnrrc.yml
    paths:
      - ./.yarn/cache/

stages:
  - build
  - test
  - release
  - deploy

build:
  stage: build
  script:
    - yarn run build
  artifacts:
    expire_in: 1 hour
    paths:
      - ./artifacts/
      - ./typechain/
  cache:
    paths:
      - ./cache/

lint:
  stage: test
  needs: []
  cache:
    policy: pull
  script:
    - yarn run lint

test:
  stage: test
  needs: ["build"]
  dependencies:
    - build
  cache:
    policy: pull
  script:
    - yarn run test
  artifacts:
    when: always
    reports:
      junit: ./test-results.xml

profile-gas:
  stage: test
  needs: ["build"]
  dependencies:
    - build
  cache:
    policy: pull
  script:
    - yarn run profile:gas
  artifacts:
    paths:
      - ./gas-profile-report.txt
    reports:
      metrics: ./gas-profile-report.txt

coverage:
  stage: test
  needs: ["build"]
  cache:
    policy: pull
  script:
    - yarn run coverage
  coverage: '/^Statements\s*:\s*([^%]+)/'
  artifacts:
    reports:
      cobertura: ./coverage/cobertura-coverage.xml
